name: Oglasnik
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.5
  animated_text_kit: ^2.2.0
  flutter_launcher_icons: ^0.7.5
  intl: ^0.16.0
  flutter_native_image: ^0.0.5
  flutter_image_compress: ^0.7.0
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.12.3
  firebase_auth: ^0.16.1
  animated_floatactionbuttons: ^0.1.0
  fab_circular_menu: ^1.0.0
  random_string: ^2.1.0
  mailgun: ^0.1.0
  flutter_dotenv: ^2.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_typeahead: ^1.8.6
  flutter_keyboard_visibility: ^3.2.1
  image_picker: ^0.6.7+4
  file_picker: ^1.13.0+1
  shared_preferences: ^0.5.8
  url_launcher: ^5.5.0
  carousel_slider: ^1.3.0
  flutter_svg: ^0.17.0
  hexcolor: ^1.0.4
  connectivity:
  fluttertoast: ^7.0.2
  zoom_widget: ^0.1.3
  photo_view: ^0.9.2
  http: ^0.12.1
  path_provider: ^1.6.7
  flushbar: ^1.10.4
  meet_network_image: ^0.1.2
  cached_network_image: ^2.2.0+1
    
    
  # cloud_firestore: ^0.13.7

  provider: ^4.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env   
    - assets/images/yoda.png
    - assets/images/nophoto.jpg
    - assets/images/logo.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 700
      
    - family: Amaranth
      fonts:
        - asset: assets/fonts/Amaranth-Regular.ttf
        - asset: assets/fonts/Amaranth-Bold.ttf
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # New app launcher icon
flutter_icons:
  image_path: 'assets/images/logo.png'
  android: true
  ios: true